package peaksoft.enums;

public enum SpecialAction {
    APPLICATION_DEVELOPMENT,
    MENTOR,
    INSTRUCTOR,
    SOFTWARE_DEVELOPER,
    ENGINEER_PROGRAMMING,
    WEBSITE_DESIGN,
    DEVELOPER,
    DATABASE_ADMINISTRATOR,
    IT_SUPPORT,
    HELPDESK,
    IT_PROJECT_MANAGER,
    PRODUCT_MANAGER,
    INFORMATION_SECURITY,
    CYBERSECURITY_ANALYST,
    INFORMATION_TECHNOLOGY_AUDITOR,
    DATA_SCIENTIST,
    NETWORK,
    COMPUTER_SYSTEMS_ADMINISTRATORS,
    CONFIGURATION,
    QA_TESTING,
    USER_EXPERIENCE_TESTING;


    }
